fix: 🐛 adding column on XRC20 table #1577
iotexproject/iotex-explorer pull request #1616
Opened 2020-09-05 18:07 UTC by ZQ-jhon

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind backend-change
> /kind ui-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Adding column for XRC20 on table, for fix issue #1577
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2020-09-05 18:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/iotexproject/iotex-explorer?pullRequest=1616) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/iotexproject/iotex-explorer?pullRequest=1616) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/iotexproject/iotex-explorer?pullRequest=1616) it.</sub>

2020-09-06 07:30 UTC, hunglmtb requested changes

2020-09-06 07:30 UTC, hunglmtb commented on src/shared/common/xrc20-token.tsx
> +      variables={{ tokenAddress }}
`GET_ADDRESS_META` requires `address` as variables, could you correct this and post some screenshots test at your local?
```
export const GET_ADDRESS_META = gql`
  query addressMeta($address: String!) {
    addressMeta(address: $address) {
      name
    }
  }
`;
```

2020-09-06 09:24 UTC, ZQ-jhon commented on src/shared/common/xrc20-token.tsx
> +      variables={{ tokenAddress }}
The component is unused, I have deleted it just now.

2020-09-06 09:26 UTC, uu-z requested changes

2020-09-06 09:26 UTC, uu-z commented on src/shared/common/xrc20-token.tsx
>  const XRC20TokenName: React.FC<{ contract: string }> = ({ contract }) => {
please update XRC20TokenName component and add hyperlink support.  it should be ` /token/{tokencontractaddress}`

2020-09-06 10:04 UTC, ZQ-jhon commented on src/shared/common/xrc20-token.tsx
>  const XRC20TokenName: React.FC<{ contract: string }> = ({ contract }) => {
Added it.

2020-09-06 12:18 UTC, uu-z approved these changes

2020-09-06 12:19 UTC, merged