Hotfix/resolve issue 1617
iotexproject/iotex-explorer pull request #1628
Opened 2020-09-16 14:26 UTC by ZQ-jhon

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind backend-change
> /kind ui-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2020-09-17 08:43 UTC, hunglmtb requested changes
seems to be missed `cross-env` in `devDependencies`

2020-09-17 12:52 UTC, ZQ-jhon commented
> seems to be missed `cross-env` in `devDependencies` @ZQ-jhon

Added it. please take a view.

2020-09-17 12:53 UTC, ZQ-jhon reviewed
Approved.

2020-09-18 15:45 UTC, hunglmtb approved these changes

2020-09-18 15:48 UTC, merged