io1j74fq09zy3lz33um2hvrc3vv2eut37rac3afnq: added scroll for data and method in confirmation model
iotexproject/iotex-explorer pull request #1785
Opened 2021-03-05 10:43 UTC by rajeshupwk

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind backend-change
> /kind ui-change
> /kind bug
> /kind cleanup

 /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
**Ans**: Add scroll in confirmation box data and method field.
**Which issue(s) this PR fixes**:

Fixes #
It the window is not big  enough. Data in confirmation model is not showing correctly.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2021-03-05 10:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/iotexproject/iotex-explorer?pullRequest=1785) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/iotexproject/iotex-explorer?pullRequest=1785) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/iotexproject/iotex-explorer?pullRequest=1785) it.</sub>

2021-03-06 03:36 UTC, anshuomomo requested changes

2021-03-06 03:36 UTC, anshuomomo commented on src/api-gateway/address-meta.json
> +    "name": "iotxplorerio"
The address is your personal wallet address, right? Why should we add it here?

2021-03-08 09:13 UTC, rajeshupwk commented on src/api-gateway/address-meta.json
> +    "name": "iotxplorerio"
@anshuomomo , I found some instructions in README.md regarding contribution and commits.So i just follow them.
![Screenshot 2021-03-08 at 2 42 21 PM](https://user-images.githubusercontent.com/18256076/110300264-afb13d00-801c-11eb-9a10-3fd14e41e2bb.png)

2021-03-11 09:11 UTC, anshuomomo commented on src/api-gateway/address-meta.json
> +    "name": "iotxplorerio"
Add meta for an address seems not about our issue.
It's the contract address on our iotex chain, not any personal addressed i think.

2021-03-23 03:06 UTC, closed without merging